openapi: 3.0.0
info:
  title: Ald-GPT API
  version: "1.0"

paths:
  /generate_code:
    post:
      summary: Generate code
      operationId: generate_code
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                app_structure:
                  type: string
                functionality:
                  type: string
      responses:
        '200':
          description: Code generated successfully
          content:
            application/json:
              schema:
                type: string
